### ISSUE TITLE
I am facing an error for the module_5 ipynb file

### ISSUE THREAD

**Issue by soumya-jit** [phreakyphoenix/MXNet-GluonCV-AWS-Coursera#1]
In the show grader output window I am facing an error after the project is being graded. The error is ModuleNotFoundError: No module named 'google' which is showing for this line: "from google.colab import drive". How can I install the google module? I have tried to install by using these commands: "!pip install google" and "!pip install google-colab". But it doesn't work for me.

**Comment by aarkodatta** [comment]
week 5 have 2 more practice assignment.please upload these code

**Comment by phreakyphoenix** [comment]
This notebook isn't meant for copy-pasting solutions for your course. 
Aside from that, that notebook already has the files installed so that the cell block is not required.
I'm closing the issue as it's unrelated to this repository's contents.

**Comment by TitanArmy** [comment]
I'm facing a problem in module 5 code help me
