### ISSUE TITLE
I want Solution of practice assignment of week 5.

### ISSUE THREAD

**Issue by vishalganjewar** [phreakyphoenix/MXNet-GluonCV-AWS-Coursera#4]
Question 1
First, let's get a particular dataset for this exercise. We will be using the CIFAR10 dataset which is built-in in MXNet in the gluon.data.vision.datasets library.

In the following cell you will complete the function definition so that it returns the CIFAR10 dataset from MXNet. The function should return both the training and the validation dataset. To make things more exciting, the function should examine both the training and validation dataset and return the index that corresponds to the first occurrence of each class in CIFAR10.

For example, the first class (label) in the CIFAR10 training dataset is 6, this corresponds to index 0 in the training dataset. For the remaining classes in the dataset, find the index in the training dataset where that class first occurs. Repeat the same process for the validation dataset. To summarize, the get_cifar_10_dataset function below should return 4 values. The CIFAR10 training dataset, the indices of the training dataset that correspond to the first occurrence of each class, The CIFAR10 validation dataset and the indices of the validation dataset that correspond to the first occurrence of each class.

CAUTION!: Although the notebook interface has internet connectivity, the autograders are not permitted to access the internet. We have already downloaded the correct models and data for you to use so you don't need access to the internet. Set the root parameter to M5_IMAGES when using a preset dataset. Usually, in the real world, you have internet access, so setting the root parameter isn't required (and it's set to ~/.mxnet by default).

def get_cifar10_dataset():
    """
    Should create the cifar 10 network and identify the dataset index of the first time each new class appears
    
    :return: tuple of training and validation dataset as well as label indices
    :rtype: (gluon.data.Dataset, dict[int:int], gluon.data.Dataset, dict[int:int])
    """
    train_data = None
    val_data = None
    train_indices = {}
    val_indicies = {}
    
    # Use `root=M5_IMAGES` for your dataset
    
    # YOUR CODE HERE
   
    raise NotImplementedError()
    
    return train_data, train_indices, val_data, val_indices

**Comment by Dhananjayan329** [comment]
do you have the answer for aws computer vision module 5

**Comment by phreakyphoenix** [comment]
This repo is not meant for solutions, closing because it's out of scope.
